fun main(){
    print("student Enrollment no.: ")
    val en= readLine()!!.toBigInteger()
    print("student Name: ")
    val name= readLine()
    print("student Branch: ")
    val branch= readLine()
    print("student Class: ")
    val cla= readLine()
    print("student Batch: ")
    val batch= readLine()
    print("student College Name: ")
    val collegename= readLine()
    print("student University Name: ")
    val universityname= readLine()
    print("student Age: ")
    val age= readLine()!!.toInt()

    println("\n***********************\n")

    println("Students's Data :")
    println("Enrollment No.:$en")
    println("Name:$name")
    println("Age:$age")
    println("Branch:$branch")
    println("Class:$cla")
    println("Batch:$batch")
    println("College Name:$collegename")
    println("University Name:$universityname")
}